### ISSUE TITLE
Service Workers

### ISSUE THREAD

**Issue by Ciao121** [utyfua/automation-extra-interception-proxy#1]
I found this package trying a method to intercept service workes request. I thiked "Unfortunately you cant handle this situation without manual requesting and then converting to puppeteer" was meaning "Unfortunaly you can't.... but this package solves the problem".
I think I'm wrong (I cannot see SW request in the developer tools of the browser). If that's right can you please helping to understand what "manual requesting and then converting to puppeteer" means?

**Comment by utyfua** [comment]
Greetings 

In my case I could see SW requests in dev tools(why not, looks strange) and I could get `page.on('request')` event about requests being made. But I was unable get response from requests from SW("context was destroyed" or stuff like that). So I just scrape all headers required to request and did it by nodejs.

This package is an advanced way of intercepting a request and also includes making requests using nodejs(thats means by "manual requesting and then converting to puppeteer") for such cases.

Known issues in managed mode:
- missing grease chip
- missing some headers
- cors flow
- - missing OPTIONS request before real request will be executed
- - headers close to be correct but not

If you really need more help, I need more information about your case.

I can also help you solve your case privately.

**Comment by Ciao121** [comment]
Thank you for your answer. This made me the process more clear.
You are right. I can see the service workers request. Not sure why I didn't saw those before...

**Comment by utyfua** [comment]
So then use [managed mode example](https://github.com/utyfua/automation-extra-interception-proxy/blob/master/samples/singlePageInterception.js).

if something goes wrong, then you need to look individually for the case.

Possibly will be enough to enable `native` mode and set `managed` for specific requests you want.
Here what you need to set in example above to do that
```js
await InterceptionUtils.wrapPage(page, {
    requestMode: "native",
})
```
```js
const response = await request.getResponse({ requestMode: "managed" })
```

One more thing. If you are using proxy you should set them separately for this library.

**Comment by utyfua** [comment]
Has the issue been resolved?

**Comment by Ciao121** [comment]
Yes. Closing it. Thank you!
