### ISSUE TITLE
Proxy arg is not working

### ISSUE THREAD

**Issue by devblack** [utyfua/automation-extra-interception-proxy#2]
The proxy handler is not working in puppeteer v20.7.3, just ignoring it and send the request without handle it.

**Comment by utyfua** [comment]
Hello

I did run `samples/singlePageInterception.js` on `puppeteer"@20.7.3` and looks like everything works as expected,

I am using `puppeteer"@20.7.2` in production. I would notice if something fishy is going on.

Can you please provide some example to reproduce the issue? I bet you are doing something wrong.

If you need to I can assist in discord(username the same as in github).

**Comment by utyfua** [comment]
Didnt notice `Proxy arg` in the title.

Did you set `requestMode` as `managed`? By default `requestMode` set as `native` which means your browser will do all the requests if possible. Thats means you should also set proxy in puppeteer itself(just like you would do without this package) and then all requests should be going throw your proxy.

So the idea here if we need to mock the data we will use provided proxy, but if not and you are using `native` mode then puppeteer will do request without relying on the library.

**Comment by devblack** [comment]
> Hello
> 
> I did run `samples/singlePageInterception.js` on `puppeteer"@20.7.3` and looks like everything works as expected,
> 
> I am using `puppeteer"@20.7.2` in production. I would notice if something fishy is going on.
> 
> Can you please provide some example to reproduce the issue? I bet you are doing something wrong.
> 
> If you need to I can assist in discord(username the same as in github).

Sure, to reproduce it.

```javascript
(async () => {

    const browser = await puppeteer.launch({
        headless: false,
    });

    // get some page
    const page = await browser.newPage();

    // attach interception commands
    await InterceptionUtils.wrapPage(page, {
        requestMode: "native",

        // optional, will be handled by https://www.npmjs.com/package/proxy-agent
        proxy: "socks5://test:test@107.179.60.118:5150"
    });

    // add some listener
    page.interceptions.addRequestListener('proxy-test', async request => {

        // get response data
        const response = await request.getResponse();

        // grab data directly from their api response
        const apiData = response.json;
        console.log(apiData)
        // result expected:
        // { ip: '107.179.60.118', ...... }
        
        // output:
        // { ip: '94......', ...... }
    });

    await page.goto('https://api.myip.com', { waitUntil: 'networkidle2' });

    // not necessary: cleaning our listener
    page.interceptions.deleteLocalRequestListener('proxy-test');

    // closing browser
    await browser.close();

})();
```

Same problem using managed or native.

**Comment by utyfua** [comment]
Please update to `0.8.2`.

There were an issue while initializing values by default. I did use setters so I didnt notice it before.

Also I did add information about [known issues in managed mode](https://github.com/utyfua/automation-extra-interception-proxy#known-issues-in-managed-mode)

Here there code I did use to test:

```
(async () => {

    const browser = await puppeteer.launch({
        headless: false,
    });

    // get some page
    const page = await browser.newPage();

    // attach interception commands
    await InterceptionUtils.wrapPage(page, {
        // you need to set requestMode to managed to use proxy
        requestMode: "managed",

        // optional, will be handled by https://www.npmjs.com/package/proxy-agent
        proxy: "socks5://test:test@some-proxy-domain.example:5150"
    });

    // you can skip `page.interceptions.addRequestListener` call if you no need to and want to use puppeteer as usual

    await page.goto('https://api.myip.com', { waitUntil: 'networkidle2' });

    console.log(await page.evaluate(() => document.body.textContent));

    // closing browser
    await browser.close();

})();
```

Let me know if the issue is resolved.

**Comment by devblack** [comment]
Is working now <3
